name: Test K8s Gateway API conformance

on:
  pull_request:
    branches:
      - '*'
    paths:
      - '.github/workflows/test-conformance.yaml'
      - 'pkg/provider/kubernetes/gateway/**'
      - 'integration/fixtures/k8s-conformance/**'
      - 'integration/k8s_conformance_test.go'

env:
  GO_VERSION: '1.23'
  CGO_ENABLED: 0

jobs:

  test-conformance:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Avoid generating webui
        run: touch webui/static/index.html

      - name: K8s Gateway API conformance test and report
        run: |
          make test-gateway-api-conformance
          git diff --exit-code

      - name: Set up KO
        uses: ko-build/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: kind.local

      - name: Upload Test Images
        run: |
          # Build and Publish our test images to the docker daemon.
          ./integration/fixtures/knative/upload-test-images.sh

      - name: Run e2e Tests
        run: |
          set -x

          # Exclude the control-plane node, which doesn't seem to expose the nodeport service.
          IPS=( $(kubectl get nodes -lkubernetes.io/hostname!=kind-control-plane -ojsonpath='{.items[*].status.addresses[?(@.type=="InternalIP")].address}') )

          # Run the tests tagged as e2e on the KinD cluster.
          go test -race -count=1 -parallel=1 -short -timeout=20m ${{ matrix.test-suite }} \
             --ingressendpoint="${IPS[0]}" \
             --ingressClass=traefik.ingress.networking.knative.dev \
             --cluster-suffix=$CLUSTER_SUFFIX